Repository PredatorFeesh/WatchParty, pull requests merged in 2020-04, with the labels that each got.

#17 WP-46 Fix jest config error
  WatchParty/client/package.json
Labels: frontend

#15 WP-42 and WP-44 implemented search bar, removed auth0
  WatchParty/client/package-lock.json
  WatchParty/client/package.json
  WatchParty/client/public/DropdownCaret.png
  WatchParty/client/public/WatchPartyLogo.png
  WatchParty/client/src/App.js
  WatchParty/client/src/auth_config.json
  WatchParty/client/src/components/Header/Header.js
  WatchParty/client/src/components/LandingPage/LandingPage.css
  WatchParty/client/src/components/LandingPage/LandingPage.js
  WatchParty/client/src/components/MovieList/MovieList.css
  WatchParty/client/src/components/MovieList/MovieList.js
  WatchParty/client/src/components/NavBar.js
  WatchParty/client/src/components/PrivateRoute.js
  WatchParty/client/src/components/Profile.js
  WatchParty/client/src/components/SearchResults/SearchResults.css
  WatchParty/client/src/components/SearchResults/SearchResults.js
  WatchParty/client/src/index.js
  WatchParty/client/src/react-auth0-spa.js
Labels: frontend

#23 WP-49 add boilerplate for backend auth
  .gitignore
  WatchParty/backend/.sequelizerc
  WatchParty/backend/Procfile
  WatchParty/backend/README.md
  WatchParty/backend/__test__/server.test.js
  WatchParty/backend/__tests__/dummy.test.js
  WatchParty/backend/app.js
  WatchParty/backend/bin/www
  WatchParty/backend/config/config.js
  WatchParty/backend/migrations/20200414233629-create-user.js
  WatchParty/backend/models/index.js
  WatchParty/backend/models/user.js
  WatchParty/backend/package-lock.json
  WatchParty/backend/package.json
  WatchParty/backend/router.js
  WatchParty/backend/seeders/20200415015509-add-three-demo-users.js
  WatchParty/backend/src/server.js
Labels: backend

#26 WP-55: Added favico + changed title + added meta tags
  WatchParty/client/public/android-chrome-192x192.png
  WatchParty/client/public/android-chrome-512x512.png
  WatchParty/client/public/apple-touch-icon.png
  WatchParty/client/public/favicon-16x16.png
  WatchParty/client/public/favicon-32x32.png
  WatchParty/client/public/favicon.ico
  WatchParty/client/public/index.html
  WatchParty/client/public/logo192.png
  WatchParty/client/public/logo512.png
  WatchParty/client/public/manifest.json
Labels: devops, frontend

#28 WP-52 fixing IMDb api call
  WatchParty/client/src/components/SearchResults/SearchResults.js
Labels: frontend

#30 wp-56: Fixed heroku-deploy and deploy-heroku mistype
  .github/workflows/backend-to-deploy.yml
  .github/workflows/backend-to-test.yml
  .github/workflows/client-to-deploy.yml
  .github/workflows/client-to-test.yml
Labels: devops

#42 Deploy frontend client to heroku
  WatchParty/client/.github/workflows/deploy-test.yml
Labels: don't merge yet

#41 WP-92 add dependencies for backend unit tests
  WatchParty/backend/.mocharc.js
  WatchParty/backend/__tests__/dummy.test.js
  WatchParty/backend/package-lock.json
  WatchParty/backend/package.json
  WatchParty/backend/test/user_model.test.js
Labels: backend

#40 WP-82 - Added additional models
  WatchParty/backend/models/follow.js
  WatchParty/backend/models/movie.js
  WatchParty/backend/models/sublist.js
  WatchParty/backend/models/user.js
  WatchParty/backend/seeders/20200415015509-add-three-demo-users.js
  WatchParty/backend/seeders/20200425210856-userarray.js
  WatchParty/backend/seeders/20200425210901-followarray.js
Labels: backend

#46 WP-96 minor misc corrections to backend
  WatchParty/backend/app.js
  WatchParty/backend/migrations/20200414233629-create-user.js
  WatchParty/backend/router.js
Labels: backend

#43 Linter part of process + install to ci
  .github/workflows/backend-to-deploy.yml
  .github/workflows/backend-to-test.yml
  .github/workflows/client-to-deploy.yml
  .github/workflows/client-to-test.yml
  .github/workflows/run_tests.yml
Labels: devops

#48 added support for 500px wid for movie searches
  WatchParty/client/src/components/SearchResults/SearchResults.css
Labels: frontend

#49 WP-97 - Add airbnb-base rules to backend linter
  WatchParty/backend/.eslintrc.js
  WatchParty/backend/package-lock.json
  WatchParty/backend/package.json
Labels: backend

#50 WP-91- Add tests for User model
  WatchParty/backend/test/user_model.test.js
Labels: backend

#47 WP-95 - Remove lint in backend (22 errors)
  WatchParty/backend/app.js
  WatchParty/backend/models/follow.js
  WatchParty/backend/models/movie.js
  WatchParty/backend/models/sublist.js
  WatchParty/backend/models/user.js
  WatchParty/backend/router.js
  WatchParty/backend/seeders/20200425210856-userarray.js
  WatchParty/backend/seeders/20200425210901-followarray.js
Labels: backend

#53 WP-101 - Remove additional lint in backend
  WatchParty/backend/app.js
  WatchParty/backend/config/config.js
  WatchParty/backend/models/follow.js
  WatchParty/backend/models/index.js
  WatchParty/backend/models/movie.js
  WatchParty/backend/models/sublist.js
  WatchParty/backend/models/user.js
  WatchParty/backend/router.js
  WatchParty/backend/seeders/20200425210856-userarray.js
  WatchParty/backend/seeders/20200425210901-followarray.js
  WatchParty/backend/test/user_model.test.js
Labels: backend

#51 WP-85, WP-89, WP-90, add tests for Follow, Sublist, Movie models
  WatchParty/backend/package-lock.json
  WatchParty/backend/package.json
  WatchParty/backend/test/follow_model.test.js
  WatchParty/backend/test/movie_model.test.js
  WatchParty/backend/test/sublist_model.test.js
Labels: backend

#45 WP-93 and WP-98 unit testing on Header and MoviePage
  WatchParty/client/package-lock.json
  WatchParty/client/package.json
  WatchParty/client/src/components/Header/Header.jsx
  WatchParty/client/src/components/Header/__test__/Header.test.jsx
  WatchParty/client/src/components/MoviePage/MoviePage.jsx
  WatchParty/client/src/components/MoviePage/__test__/MoviePage.test.jsx
  WatchParty/client/src/components/SearchResults/SearchResults.jsx
  WatchParty/client/src/setupTests.js
Labels: frontend

#56 WP-74 frontend lint fixes
  WatchParty/client/src/__test__/App.test.js
  WatchParty/client/src/components/Header/Header.jsx
  WatchParty/client/src/components/LandingPage/LandingPage.jsx
  WatchParty/client/src/components/MoviePage/MoviePage.jsx
  WatchParty/client/src/components/SearchResults/SearchResults.jsx
  WatchParty/client/src/setupTests.js
Labels: frontend

#55 WP-102 - adjust backend dependencies
  WatchParty/backend/package-lock.json
  WatchParty/backend/package.json
Labels: backend

#59 Ref change
  WatchParty/client/.github/workflows/deploy-test.yml
Labels: devops

#58 Fixed some linting backend errors + added mocha to env
  WatchParty/backend/.eslintrc.js
  WatchParty/backend/test/follow_model.test.js
  WatchParty/backend/test/movie_model.test.js
  WatchParty/backend/test/sublist_model.test.js
Labels: backend

#60 WP-100 search results component unit tests
  WatchParty/client/src/components/MoviePage/__test__/MoviePage.test.jsx
  WatchParty/client/src/components/SearchResults/SearchResults.jsx
  WatchParty/client/src/components/SearchResults/__test__/SearchResults.test.jsx
Labels: frontend

#57 WP-94-selenium-test-movie-search
  WatchParty/client/selenium/README.txt
  WatchParty/client/selenium/movieResultTest.py
Labels: frontend
